# Generated by Django 3.2.20 on 2023-07-08 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
